#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
static_resources:
  listeners:
    - name: "net/http"
      protocol_type: "HTTP"
      address:
        socket_address:
          address: "0.0.0.0"
          port: 8888
      filter_chains:
        filters:
          - name: dgp.filter.httpconnectionmanager
            config:
              route_config:
                routes:
                  - match:
                      prefix: "/user"
                    route:
                      cluster: "user"
                      cluster_not_found_response_code: 505
              http_filters:
                - name: dgp.filter.http.httpproxy
                  config:
                - name: dgp.filter.http.cors
                  config:
                    allow_origin:
                      - api.dubbo.com
                    allow_methods: ""
                    allow_headers: ""
                    expose_headers: ""
                    max_age: ""
                    allow_credentials: false
      config:
        idle_timeout: 5s
        read_timeout: 5s
        write_timeout: 5s
  clusters:
    - name: "user"
      lb_policy: "lb"
      endpoints:
        - id: 1
          socket_address:
            address: 127.0.0.1
            port: 1314
  shutdown_config:
    timeout: "60s"
    step_timeout: "10s"
    reject_policy: "immediacy"

config-center:
  type: "nacos"
  enable: true

nacos:
  server_configs:
    - ip_addr: "localhost"
      port: 8848
      scheme: "http"
      contextPath: "/nacos"
    - ip_addr: "localhost"
      port: 8848
      scheme: "http"
      contextPath: "/nacos"
  client-config:
    cache_dir: "./.cache"
    log_dir: "./.log"
    not_load_cache_at_start: true
    namespace_id: "dubbo-go-pixiu"
  data-id: "pixiu.yaml"
  group: "DEFAULT_GROUP"

log:
  level: "debug"
  development: true
  disableCaller: false
  disableStacktrace: false
  sampling:
  encoding: "console"

  # encoder
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "time"
    nameKey: "logger"
    callerKey: "caller"
    stacktraceKey: "stacktrace"
    lineEnding: ""
    levelEncoder: "capitalColor"
    timeEncoder: "iso8601"
    durationEncoder: "seconds"
    callerEncoder: "short"
    nameEncoder: ""

  outputPaths:
    - "stderr"
  errorOutputPaths:
    - "stderr"
  initialFields:

